### ISSUE TITLE
isWebpSupported returns false in Firefox 70

### ISSUE THREAD

**Issue by EliteMasterEric** [DonRai/react-image-webp#39]
Firefox is stated to have officially implemented support for WebP images in Firefox 65, and yet in Firefox 70.0.1 this library fails to detect support.

[A CodeSandbox for demonstration](https://codesandbox.io/s/react-webp-test-kf8rw)

This CodeSandbox displays No on Firefox 70.0.1 but displays Yes on Chrome 78.0.3904.97.

[The release notes for WebP support](https://hacks.mozilla.org/2019/01/firefox-65-webp-flexbox-inspector-new-tooling/)

Not that [this issue also occurs in a similar library](https://github.com/Horat1us/react-img-webp/issues/5) indicating that this may be a browser problem.

EDIT: I found a snippet from OurCodeWorld, which I added to the CodeSandbox, which does return the correct response.

**Comment by MasterEric** [comment]
Still an issue a year later.

**Comment by EliteMasterEric** [comment]
Just quickly checked and on Firefox 110.0.1, the CodeSandbox works. Either this repo or Firefox fixed the issue.
