### ISSUE TITLE
Why not using picture element instead

### ISSUE THREAD

**Issue by ikhattab** [DonRai/react-image-webp#40]
I wonder why we are not using [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element here [instead](https://css-tricks.com/using-webp-images/#article-header-id-3). given the example, in the README we can do

```jsx
<picture>
  <source srcSet={require('./path/to/webp')} type="image/webp" />
  <source srcSet={require('./path/to/image')} type="image/png" />
  <img src={require('./path/to/image')} />
</picture>
```

p.s: I'm not trying to attack the work done here, This is a cool library I liked it and use it and even one of my colleagues submitted PR here.

**Comment by DonRai** [comment]
@ikhattab  yep, you're right, this library for very specific cases. And I also recommend using <picture>. 
I updated Readme.
